// templates/tool_template.rs
// Template version: 1.0.0

use serde_json::Value;

pub trait TemplatedTool {
    fn name(&self) -> &str;
    fn description(&self) -> &str;

    fn execute(&self, input: Value) -> Result<Value, String>;

    fn log_telemetry(&self, success: bool, duration_ms: u128) {
        let _ = (success, duration_ms);
        // Hook point: forward to Phoenix telemetry pipeline.
    }

    fn generate_readme(&self) -> String {
        format!(
            "# {}\n\n{}\n\nGenerated by Phoenix template v1.0.0\n",
            self.name(),
            self.description()
        )
    }
}

